#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          serf
# Required-Start:    $local_fs $remote_fs $network $syslog $named 
# Required-Stop:     $local_fs $remote_fs $network $syslog $named 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/Stop A highly-available key value store for shared configuration and service discovery
### END INIT INFO

NAME=serf
SERFPATH="/opt/serf"
SERFBIN="$SERFPATH/$NAME"
CONFFILE="/etc/avahi-ps-serf.conf"
PIDFILE="/var/run/serf.pid"
IDNUM=50
HOST_ID=${SERFPATH}/HostID

BIND_IP="0.0.0.0"
MACHINE=$(uname -n)
OPTS='-event-handler user:cleareinfo=/etc/serf/handlers/handle'
SERF_RPC_ADDR="127.0.0.1:4001"
SERF_BIND="5000"
SERF_LOG="/tmp/serf.log"

GTCONF="/etc/getinconf-client.conf"

test -f $GTCONF && . $GTCONF || exit 0

PUBLIC_DEVICE=${INTERNAL_DEV}
PUBLIC_IP=$(ip addr show dev $PUBLIC_DEVICE|grep "global.* $PUBLIC_DEVICE\$"|awk '{print $2}'|awk -F "/" {'print $1'})

test -f $CONFFILE && . $CONFFILE

[ -z "$SERF_JOIN" ] &&  PEERS="" || PEERS="-join $SERF_JOIN"


calculate_name() {
   PORT=${1:-""}
	[ ! -f $HOST_ID ] && cat /dev/urandom | env LC_CTYPE=C tr -cd 'a-f0-9' | head -c $IDNUM |md5sum|cut -d " " -f 1 > $HOST_ID
   echo -n $(cat $HOST_ID)"-${PORT}"
}

start() {
	[ -f $PIDFILE ] && $(netstat -ant|grep ${SERF_RPC_ADDR}|grep -q LISTEN) && exit 3;
	[ ! -f $SERFBIN ] && { echo "serf is not installed in $SERFBIN."| tee -a $SERF_LOG ; exit 0; }
	$(echo "${PUBLIC_IP}"| grep -qvE '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' ) && { echo "Try use SERF with non-IPv4."| tee -a $SERF_LOG ; exit 1; }
	$(echo "${PUBLIC_IP}"| grep -qE '^127\.') && { echo "Try use SERF in localhost IPs"| tee -a $SERF_LOG ; exit 2; }
  [ ! -z "${ADVERTISE_IP}" ] && { OPTS="${OPTS} -advertise=${ADVERTISE_IP}:${SERF_BIND}" ; } 
	$SERFBIN agent -node=$(calculate_name $SERF_BIND) -bind=${PUBLIC_IP}:${SERF_BIND} -rpc-addr=${SERF_RPC_ADDR} $PEERS $OPTS >> $SERF_LOG 2>&1 & 
	echo $! > $PIDFILE  
}
stop() {
  kill -9 $(cat $PIDFILE)
  rm $PIDFILE
}
restart() {
  stop
  sleep 0.5
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
  ;;
esac

exit 0


