#!/bin/bash
#Handler for any user or query event
#All events will be named user-$event or query-$event

HANDLER_DIR="/etc/serf/handlers"
#echo "HANDLING"$SERF_USER_EVENT >> /test1.txt

if [ "$SERF_EVENT" = "user" ]; then
	EVENT="user-$SERF_USER_EVENT"
elif [ "$SERF_EVENT" = "query" ]; then
	EVENT="query-$SERF_QUERY_NAME"
else
	EVENT=$SERF_EVENT
fi

HANDLER="$HANDLER_DIR/$EVENT"
[ -f "$HANDLER" -a -x "$HANDLER" ] && exec "$HANDLER" || :

